
# ABC順？に並びかえないと指摘
Bundler/OrderedGems:
  Exclude:
    - 'Gemfile'

Layout/CommentIndentation:
  Exclude:
    - 'app/controllers/application_controller.rb'
    - 'app/helpers/sessions_helper.rb'

Layout/EmptyLinesAroundClassBody:
  Exclude:
    - 'app/controllers/orders_controller.rb'
    - 'app/controllers/users_controller.rb'
    - 'app/uploaders/image_uploader.rb'
    - 'app/uploaders/images_uploader.rb'
    - 'test/controllers/sessions_controller_test.rb'
    - 'test/controllers/static_pages_controller_test.rb'
    - 'test/controllers/users_controller_test.rb'

# private下のインデント指摘
Layout/IndentationConsistency:
  Exclude:
    - 'app/controllers/orders_controller.rb'
    - 'app/controllers/users_controller.rb'
    - 'config/routes.rb'

# private下のインデント指摘
Layout/IndentationWidth:
  Exclude:
    - 'app/controllers/orders_controller.rb'
    - 'app/controllers/users_controller.rb'

Layout/SpaceAroundOperators:
  Exclude:
    - 'app/models/order.rb'
    - 'config/initializers/carrierwave.rb'
    - 'app/decorators/order_decorator.rb'
    - 'app/decorators/user_decorator.rb'
    - 'app/models/order.rb'
    - 'app/models/user.rb'

Metrics/AbcSize:
  Max: 55

Metrics/BlockLength:
  Max: 39

Metrics/ClassLength:
  Max: 103

Metrics/MethodLength:
  Max: 18

Naming/VariableNumber:
  Exclude:
    - 'app/controllers/orders_controller.rb'
    - 'app/decorators/order_decorator.rb'
    - 'app/models/order.rb'
    - 'db/migrate/20200423145637_add_images_to_orders.rb'

Style/AsciiComments:
  Exclude:
    - 'Gemfile'
    - 'app/controllers/application_controller.rb'
    - 'app/controllers/sessions_controller.rb'
    - 'app/helpers/sessions_helper.rb'
    - 'app/models/user.rb'
    - 'app/uploaders/image_uploader.rb'
    - 'app/uploaders/images_uploader.rb'
    - 'config/initializers/carrierwave.rb'
    - 'config/routes.rb'

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/MixinUsage:
  Exclude:
    - 'bin/setup'
    - 'bin/update'

Style/NumericLiterals:
  MinDigits: 15

Style/RedundantBegin:
  Exclude:
    - 'bin/yarn'

Layout/LineLength:
  Max: 220
