inherit_from: .rubocop_todo.yml

# 複数行での「lambda」で「->」による省略記法を許可
Lambda:
  Enabled: false

# モジュール名::クラス名の定義を許可
ClassAndModuleChildren:
  Enabled: false

# メソッド名のprefixに「set_」「get_」を許可
AccessorMethodName:
  Enabled: false

# クラスにコメントを残さない
Documentation:
  Enabled: false

# 「and」「or」の使用を許可
AndOr:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

# ハッシュリテラルのキーが複数行にまたがる場合、それらのキーを整列させる
Layout/HashAlignment:
  Enabled: false

# 文字の長さの制限
LineLength:
  Enabled: false

# 日本語でのコメントを許可
Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RedundantCondition:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

# シングルクォーテーション
Style/StringLiterals:
  Enabled: false

# テスト環境
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/ClassLength:
  Enabled: false

# ハッシュの記法はロケット記法ではなくruby1.9のハッシュ記法を使いますよ」ということを表します。
HashSyntax:
  EnforcedStyle: ruby19

AllCops:
  Exclude:
    - bin/*
    - db/schema.rb
    - config/unicorn.rb
    - config/unicorn_staging.rb
    - tmp/**/*
    - 'test/test_helper.rb'
