
# ABC順？に並びかえないと指摘
Bundler/OrderedGems:
  Exclude:
    - 'Gemfile'

Layout/CommentIndentation:
  Exclude:
    - 'app/controllers/application_controller.rb'
    - 'app/helpers/sessions_helper.rb'

#Layout/EmptyLinesAroundClassBody:
  #Exclude:
    - 'app/controllers/orders_controller.rb'
    - 'app/controllers/users_controller.rb'
    - 'app/uploaders/image_uploader.rb'
    - 'app/uploaders/images_uploader.rb'
    - 'test/controllers/sessions_controller_test.rb'
    - 'test/controllers/static_pages_controller_test.rb'
    - 'test/controllers/users_controller_test.rb'

# private下のインデント指摘
Layout/IndentationConsistency:
  Exclude:
    - 'app/controllers/orders_controller.rb'
    - 'app/controllers/users_controller.rb'
    - 'config/routes.rb'

# private下のインデント指摘
Layout/IndentationWidth:
  Exclude:
    - 'app/controllers/orders_controller.rb'
    - 'app/controllers/users_controller.rb'

Layout/SpaceAroundOperators:
  Exclude:
    - 'app/models/order.rb'
    - 'config/initializers/carrierwave.rb'
    - 'app/decorators/order_decorator.rb'
    - 'app/decorators/user_decorator.rb'
    - 'app/models/order.rb'
    - 'app/models/user.rb'

Metrics/AbcSize:
  Max: 55

Metrics/BlockLength:
  Max: 39

Metrics/ClassLength:
  Max: 103

Metrics/MethodLength:
  Max: 18

Naming/VariableNumber:
  Exclude:
    - 'app/controllers/orders_controller.rb'
    - 'app/decorators/order_decorator.rb'
    - 'app/models/order.rb'
    - 'db/migrate/20200423145637_add_images_to_orders.rb'

Style/AsciiComments:
  Exclude:
    - 'Gemfile'
    - 'app/controllers/application_controller.rb'
    - 'app/controllers/sessions_controller.rb'
    - 'app/helpers/sessions_helper.rb'
    - 'app/models/user.rb'
    - 'app/uploaders/image_uploader.rb'
    - 'app/uploaders/images_uploader.rb'
    - 'config/initializers/carrierwave.rb'
    - 'config/routes.rb'

# Offense count: 4
# Cop supports --auto-correct.
# Configuration parameters: UseHashRocketsWithSymbolValues, PreferHashRocketsForNonAlnumEndingSymbols.
# SupportedStyles: ruby19, hash_rockets, no_mixed_keys, ruby19_no_mixed_keys
Style/HashSyntax:
  EnforcedStyle: hash_rockets

# Offense count: 2
Style/IdenticalConditionalBranches:
  Exclude:
    - 'app/controllers/users_controller.rb'

# Offense count: 3
# Cop supports --auto-correct.
Style/IfUnlessModifier:
  Exclude:
    - 'app/models/order.rb'
    - 'app/models/user.rb'

# Offense count: 2
Style/MixinUsage:
  Exclude:
    - 'bin/setup'
    - 'bin/update'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: literals, strict
Style/MutableConstant:
  Exclude:
    - 'app/models/user.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: Strict.
Style/NumericLiterals:
  MinDigits: 15

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: AllowSafeAssignment, AllowInMultilineConditions.
Style/ParenthesesAroundCondition:
  Exclude:
    - 'app/models/order.rb'

# Offense count: 4
# Cop supports --auto-correct.
# Configuration parameters: PreferredDelimiters.
Style/PercentLiteralDelimiters:
  Exclude:
    - 'app/controllers/application_controller.rb'
    - 'app/uploaders/image_uploader.rb'
    - 'app/uploaders/images_uploader.rb'
    - 'config/spring.rb'

# Offense count: 1
# Cop supports --auto-correct.
Style/RedundantBegin:
  Exclude:
    - 'bin/yarn'

# Offense count: 2
# Cop supports --auto-correct.
Style/RedundantCondition:
  Exclude:
    - 'app/uploaders/image_uploader.rb'
    - 'app/uploaders/images_uploader.rb'

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: SafeForConstants.
Style/RedundantFetchBlock:
  Exclude:
    - 'config/puma.rb'

# Offense count: 1
# Cop supports --auto-correct.
Style/RedundantSelf:
  Exclude:
    - 'app/models/user.rb'

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: ConvertCodeThatCanStartToReturnNil, AllowedMethods.
# AllowedMethods: present?, blank?, presence, try, try!
Style/SafeNavigation:
  Exclude:
    - 'app/controllers/sessions_controller.rb'
    - 'app/helpers/sessions_helper.rb'

# Offense count: 5
# Cop supports --auto-correct.
# Configuration parameters: AllowModifier.
Style/SoleNestedConditional:
  Exclude:
    - 'app/models/order.rb'

# Offense count: 2
# Cop supports --auto-correct.
Style/StderrPuts:
  Exclude:
    - 'bin/yarn'

# Offense count: 1
# Cop supports --auto-correct.
Style/StringConcatenation:
  Exclude:
    - 'app/helpers/application_helper.rb'

# Offense count: 115
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, ConsistentQuotesInMultiline.
# SupportedStyles: single_quotes, double_quotes
Style/StringLiterals:
  Enabled: false

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: single_quotes, double_quotes
Style/StringLiteralsInInterpolation:
  Exclude:
    - 'bin/yarn'

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: .
# SupportedStyles: percent, brackets
Style/SymbolArray:
  EnforcedStyle: percent
  MinSize: 5

# Offense count: 1
# Cop supports --auto-correct.
Style/SymbolLiteral:
  Exclude:
    - 'config/routes.rb'

# Offense count: 14
# Cop supports --auto-correct.
# Configuration parameters: AutoCorrect, AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Layout/LineLength:
  Max: 206
